### Testing Hello world app
GET http://localhost:3007

### List all last

GET http://localhost:3007/allPost/

### List all words last week

GET http://localhost:3007/lastWeekPost


### List all last 600 stories
GET http://localhost:3007/last600stories

### List all last 25 stories
GET http://localhost:3007/last25stories